### ISSUE TITLE
Remove default autohide for notifications

### ISSUE THREAD

**Issue by exp625** [JamFactoryApp/jamfactory-web#29]
I think it's better to increase the duration for which these notifications are visible and not make them stay there forever.

Another solution, as a compromise, would be to implement a notification box that can be shown when clicking a button and which contains unseen notifications as well as a badge indicating how many notifications have not been seen by the user yet.

On the other hand this seems like overkill in contrast to the amount of notifications that we will show to the user.

_Originally posted by @DrJoLe in https://github.com/JamFactoryApp/jamfactory-web/pull/28#discussion_r611899220_

**Comment by Pallemann** [comment]
The new implementation of notifications alleviates this issue.
