### ISSUE TITLE
Think about using another socket.io client implementation

### ISSUE THREAD

**Issue by DrJoLe** [JamFactoryApp/jamfactory-web#4]
The one currently in use seems outdated or not properly configured.

**Comment by DrJoLe** [comment]
https://github.com/gorilla/websocket actually looks pretty simple to implement. Would like to tackle

**Comment by exp625** [comment]
I would recommend not using a golang package in an Angular project.

**Comment by DrJoLe** [comment]
Challenge accepted

**Comment by DrJoLe** [comment]
#10
