### ISSUE TITLE
Handle opening link of expired JamSession

### ISSUE THREAD

**Issue by Pallemann** [JamFactoryApp/jamfactory-web#43]
Any user when trying to open a link  `jamfactory.app/jam/12345` to an expired JamSession will not be redirected to the main page `https://jamfactory.app/`, but instead looks at an empty white page.

Suggested solution:

- Check if JamSession still exists when opening a link containing a JamLabel, if JamSession does not exist, redirect to main page

**Comment by exp625** [comment]
I can only reproduce this error, when the backend is not reachable. Adding a timeout detection would fix this problem.
