### ISSUE TITLE
Don't redirect to nonexisting JamSession

### ISSUE THREAD

**Issue by DrJoLe** [JamFactoryApp/jamfactory-web#5]

**Comment by DrJoLe** [comment]
JamFactoryApp/jamfactory-backend@d564a2b04ae6025afac9d93ad15085dfe7d0162d

**Comment by exp625** [comment]
Was already fixed with 7e8bd6a98194089696313c4139cbf3b287f5a17a

**Comment by DrJoLe** [comment]
kind of. Backend should not reply with JamSession data if session is already expired (e.g. after server restart).

**Comment by exp625** [comment]
Of course, but this is not a frontend issue
