### ISSUE TITLE
Notification Button in the playback component

### ISSUE THREAD

**Issue by exp625** [JamFactoryApp/jamfactory-web#71]
Currently, the notification button constantly suggests that there is a notification. However, when you click the button, nothing is displayed.
This is quite unintuitive. 

Perhaps the notifications in the sidebar are usually hidden in a fold-out menu (or only the first one shown). Clicking the notification button then opens the sidebar and the notifications unfold.

**Comment by exp625** [comment]
Button now opens the menu and the red dot is only displayed when there are notifications.

However, multiple notifications break the sidebar

**Comment by Pallemann** [comment]
Multiple notifications are being handled correctly now.
